spring:
  datasource:
    driver-class-name: org.h2.Driver
    hikari:
      jdbc-url: jdbc:h2:mem://localhost/~/testdb;MODE=MYSQL;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        storage_engine: innodb
    hibernate:
    ddl-auto: create-drop
#    ddl-auto: update
  h2:
    console:
      enabled: true
  data:
    elasticsearch:
      cluster-name: es-docker-cluster
      host: localhost
      port: 9200
  devtools:
    livereload:
      enabled: true

springdoc:
  packagesToScan: com.milkit.app
  swagger-ui:
    path: /swagger-ui.html

server:
  tomcat:
    uri-encoding: UTF-8
  servlet:
    encoding:
      force: true 
      charset: UTF-8
      enabled: true
       
logging:
  level:
    root: INFO
    com:
      milkit: INFO
    org:
      hibernate:
        SQL: INFO
        type:
          descriptor:
            sql:
              BasicBinder: INFO
      springframework:
        security: INFO
